[NCP-3463] some text added
mileweb/ngportal-language pull request #375
Opened 2023-08-08 07:06 UTC by jungho73

2023-08-08 17:04 UTC, burtonquantil requested changes
One word is misspelled.

2023-08-08 17:04 UTC, burtonquantil commented on en_US.json
> +	"report.range.txt.duration": "Duraton",
This should be "Duration"

2023-08-09 00:11 UTC, jungho73 commented on en_US.json
> +	"report.range.txt.duration": "Duraton",
I fixed the word misspelled.
Thanks.

2023-08-09 00:19 UTC, chiraags approved these changes
Good to merge.

2023-08-09 00:38 UTC, burtonquantil approved these changes
OK to merge

2023-08-09 08:37 UTC, merged