[NCP-3457] some hints were changed by suggestions
mileweb/ngportal-language pull request #406
Opened 2024-07-29 06:18 UTC by jungho73

2024-07-29 07:54 UTC, Jianghai-Quantil commented on zh-Hans.json
> +	"reportQuery.page.validation.count.group.by": "请选择最多两项。",
Please keep the original texts.

2024-07-29 07:54 UTC, Jianghai-Quantil commented on zh-Hans.json
> +	"reportQuery.page.validation.count.wildcard": "请选择单个通配符主机名。",
Please keep the original text.

2024-07-29 07:54 UTC, Jianghai-Quantil requested changes
Requested some changes.

2024-07-29 15:02 UTC, burtonquantil approved these changes
The English text looks OK.

2024-07-30 01:17 UTC, jungho73 commented
> Requested some changes.

kept the original texts.

2024-07-30 03:28 UTC, Jianghai-Quantil approved these changes
OK. Good to merge.

2024-07-30 04:21 UTC, merged