[NCP-3679] improve the message when creating/updating is submitted
mileweb/ngportal-language pull request #407
Opened 2024-08-01 05:43 UTC by jungho73

2024-08-01 08:11 UTC, Jianghai-Quantil commented on zh-Hans.json
> +	"edgeHostname.create.success.modal.content.2": "边缘主机名已成功创建。边缘主机名生效需要几分钟时间。您可以打开详细信息页面并在 {history} 下拉列表中检查状态。请确保状态为成功且边缘主机名已生效，然后才能在您的 DNS 记录中使用边缘主机名。",
Please change it to:

调度域名已成功创建。调度域名的部署需要几分钟时间。您可以打开详请页面并在 {操作历史} 下拉列表中检查部署状态。请确保域名已部署成功且配置生效，才在DNS记录中使用该调度域名。

2024-08-01 08:13 UTC, Jianghai-Quantil commented on zh-Hans.json
> +	"edgeHostname.update.accepted.modal.content": "边缘主机名更新已接受。更改生效需要几分钟时间。您可以在 {history} 下拉列表中检查状态。在 DNS 记录中使用边缘主机名之前，请检查状态是否为“成功”且更改是否已生效。",
Please change it to:

调度域名更新请求已接受。调度域名的部署需要几分钟时间。您可以打开详请页面并在 {操作历史} 下拉列表中检查部署状态。请确保域名已部署成功且配置生效，才在DNS记录中使用该调度域名。

2024-08-01 09:47 UTC, Jianghai-Quantil requested changes
Requested some changes

2024-08-01 18:40 UTC, burtonquantil requested changes
Minor text change requested

2024-08-01 18:40 UTC, burtonquantil commented on en_US.json
> +	"edgeHostname.update.accepted.modal.content": "The edge hostname update has been accepted. It will take a few minutes before the change takes effect. You can check the status in the {history} dropdo
Sorry for the confusion. Add the word "is":

 **Please check that the status is ‘Succeeded’**

2024-08-01 18:40 UTC, burtonquantil commented on en_US.json
> +	"edgeHostname.create.success.modal.content.2": "The edge hostname has been successfully created. It will take a few minutes before the edge hostname takes effect. You can open the details page and c
Change one word:

**Please make sure that the status is ‘Succeeded’**

2024-08-02 01:13 UTC, jungho73 commented
@burtonquantil @Jianghai-Quantil 
I updated some text again according to comments from the issue .
Please check again your changes requested.

2024-08-02 01:15 UTC, burtonquantil approved these changes
The English text is OK.

2024-08-02 01:43 UTC, Jianghai-Quantil commented
@jungho73 The Chinese texts are not changed as requested. Can you double check?

2024-08-02 01:57 UTC, jungho73 commented
> @jungho73 The Chinese texts are not changed as requested. Can you double check?

@Jianghai-Quantil  Since the English sentence changed, I thought the Chinese you requested should be changed first. First, I made the corrections you requested. Please review again.

2024-08-02 02:17 UTC, Jianghai-Quantil commented on zh-Hans.json
> +	"edgeHostname.create.success.modal.content.2": "调度域名已成功创建。调度域名的部署需要几分钟时间。您可以打开详请页面并在 {history} 下拉列表中检查部署状态。请确保域名已部署成功且配置生效，才在DNS记录中使用该调度域名。",
Please replace {history} with {操作历史}.

When the language selected by user is Chinese, there won't be the label for the dropdown won't History.

2024-08-02 02:17 UTC, Jianghai-Quantil commented on zh-Hans.json
> +	"edgeHostname.update.accepted.modal.content": "调度域名更新请求已接受。调度域名的部署需要几分钟时间。您可以打开详请页面并在 {history} 下拉列表中检查部署状态。请确保域名已部署成功且配置生效，才在DNS记录中使用该调度域名。",
Please replace {history} with {操作历史}.

When the language selected by user is Chinese, there won't be the label for the dropdown won't History.

2024-08-02 02:45 UTC, jungho73 commented on zh-Hans.json
> +	"edgeHostname.update.accepted.modal.content": "调度域名更新请求已接受。调度域名的部署需要几分钟时间。您可以打开详请页面并在 {history} 下拉列表中检查部署状态。请确保域名已部署成功且配置生效，才在DNS记录中使用该调度域名。",
As you can see when you select in Chinese, the label will use this below.
"button.menu.text.deployment.history": "部署历史",
That means  {history} will be converted to  "部署历史".

But do you mean to want to change  "部署历史" to "操作历史", right?
if it is right, I will add new item for {history} edgehostname page.

2024-08-02 03:30 UTC, Jianghai-Quantil commented on zh-Hans.json
> +	"edgeHostname.update.accepted.modal.content": "调度域名更新请求已接受。调度域名的部署需要几分钟时间。您可以打开详请页面并在 {history} 下拉列表中检查部署状态。请确保域名已部署成功且配置生效，才在DNS记录中使用该调度域名。",
@jungho73 Either "部署历史" or "操作历史" is fine. Let's use "部署历史" to be consistent with the label. 

Don't know that {history} is a variable to be expanded. Had thought {} is used for styling. 

Then no change is required. Approving the PR.

2024-08-02 03:31 UTC, Jianghai-Quantil approved these changes
Good to merge.

2024-08-02 03:34 UTC, merged