[NCP-3434] Added texts.
mileweb/ngportal-language pull request #413
Opened 2024-11-06 03:11 UTC by chiraags

2024-11-06 11:55 UTC, Jianghai-Quantil commented on zh-Hans.json
> +	"property.label.enableIPv6Origin.option.enable": "使能够",
Please change it to "启用"

2024-11-06 12:04 UTC, Jianghai-Quantil commented on zh-Hans.json
> +	"property.label.enableIPv6Origin.tips": "启用使用 IPv6 地址访问属性的源服务器。禁用后，即使您的源支持 IPv6，也只会使用 IPv4 地址。如果您的源仅可通过 IPv6 地址访问，请将“origins”中的“directConnection”设置为“noDirect”，并将“Follow Client IP Version”设置为“strict”
Please change it to:
"表示是否使用源站的IPv6地址回源。禁用状态下，cache服务器回源时只会连接源站的IPv4地址，即便源站支持IPv6。启用状态下，如果您的源站仅支持IPv6，请将‘直接连接’设为‘不直连，使用父缓存’，并且将‘是否遵循客户端IP协议’设为‘严格遵循’，避免回源失败，因为并非所有的边缘节点都支持IPv6。"

2024-11-06 12:04 UTC, Jianghai-Quantil commented on zh-Hans.json
> +	"property.label.followClientIPVersion": "跟随客户端IP版本",
Please change it to: "遵循客户端IP协议"

2024-11-06 12:05 UTC, Jianghai-Quantil commented on zh-Hans.json
> +	"property.label.followClientIPVersion.option.auto": "汽车",
please change it to: "自动选择"

2024-11-06 12:05 UTC, Jianghai-Quantil commented on zh-Hans.json
> +	"property.label.followClientIPVersion.option.off": "离开",
Please change it to "不遵循"

2024-11-06 12:05 UTC, Jianghai-Quantil commented on zh-Hans.json
> +	"property.label.followClientIPVersion.option.strict": "严格的",
please change it to: "严格遵循"

2024-11-06 12:06 UTC, Jianghai-Quantil commented on zh-Hans.json
> +	"property.label.followClientIPVersion.placeholder": "选择寻址方法",
please change it to: "是否遵循客户端IP协议"

2024-11-06 12:11 UTC, Jianghai-Quantil commented on zh-Hans.json
> +	"property.label.followClientIPVersion.tips": "如果需要向原点发出请求来获取内容，则控制是否匹配客户端使用的寻址方法。 “auto”：首选与客户端相同的 IP 寻址方法，但如果需要，可以使用另一个版本作为备份。 “strict”：必须匹配与客户端相同的寻址方法。 “off”：选择原始 IP，无论客户端使用何种 IP 寻址方法。建议使用“off”。",
Please change it to: 
‘自动选择’表示优先按照客户端IP协议版本选择相同协议的回源地址，如果回源失败则选择非同协议的IP地址回源。‘严格遵循’表示严格遵循客户端IP协议版本选择同协议的回源地址。‘不遵循’表示不考虑客户端IP协议版本，随机选择回源地址。推荐使用‘不遵循’。

2024-11-06 12:12 UTC, Jianghai-Quantil requested changes
Some changes requested.

2024-11-06 19:40 UTC, chiraags commented
@Jianghai-Quantil I updated the texts. Please review.

2024-11-07 01:33 UTC, Jianghai-Quantil approved these changes
Good to merge.

2024-11-07 02:09 UTC, merged